---
mongodb_repository_config:
  v2.6:
    repository: deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
    package: mongodb-org
    key: EA312927
  v3.0:
    repository: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse
    package: mongodb-org
    key: EA312927
  v3.2:
    repository: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse
    package: mongodb-org
    key: EA312927
  v3.4:
    repository: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse
    package: mongodb-org
    key: A15703C6
