---
# Configure ssh-keys on Bastion(jumphost) Server for Demo Project infrastructure

- name: Ensure ~/.ssh directory exists
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Install SSH Private Key
  copy:
    src: ccube_rsa
    owner: root
    group: root
    dest: /root/.ssh/id_rsa
    mode: 0600
    
- name: Install SSH Public Key
  copy:
    src: authorized_keys
    owner: root
    group: root
    dest: /root/.ssh/id_rsa.pub
    mode: 0600

- name: Install authorized_keys Public Key
  copy:
    src: authorized_keys
    owner: root
    group: root
    dest: /root/.ssh/authorized_keys
    mode: 0600